lib/awesome_chat_web/router.ex
defmodule AwesomeChatWeb.Router do
  use AwesomeChatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AwesomeChatWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create, :edit, :show, :update, :delete]
    get "/login", UserController, :login
    post "/login", UserController, :do_login
    delete "/logout", UserController, :logout
  end

  # Other scopes may use custom stacks.
  # scope "/api", AwesomeChatWeb do
  #   pipe_through :api
  # end
end

lib/awesome_chat_web/views/layout_view.ex
defmodule AwesomeChatWeb.LayoutView do
  use AwesomeChatWeb, :view

  def authenticated_user(conn) do
    Plug.Conn.get_session(conn, :authenticated_user)
  end
end

lib/awesome_chat_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello AwesomeChat!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
            <% user = authenticated_user(@conn) %>
            <%= if(user) do %>
              <li><%= link(user.name, to: user_path(@conn, :show, user)) %></li>
              <li><%= link("logout", to: user_path(@conn, :logout), method: :delete) %></li>
            <% else %>
              <li><%= link("register", to: user_path(@conn, :new)) %></li>
              <li><%= link("login", to: user_path(@conn, :login)) %></li>
            <% end %>
          </ul>
        </nav>
      </header>
      <div class="container">
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      </div>
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>